// Generates Firestore rules shape validators from the zod contract, so
// the rules can never drift from the schemas the app writes with. House
// style (data-contracts): generate validators only for collections the
// client writes directly; authorization stays hand-written around them.
//
// Known non-goals, so nobody rediscovers them as bugs: refinements
// (regex, min length) and the contents of lists and nested maps are not
// checked, only their types. A collection needing those wants the
// function write path.
import { z } from 'zod';

export interface ValidatedCollection {
  /** Used in the function name: isValid<Name>. */
  name: string;
  schema: z.ZodObject;
}

type AnySchema = z.ZodType & { _zod: { def: { type: string } } };

/** Turns one field's schema into a rules expression about `ref`. */
function typeCheck(
  schema: AnySchema,
  ref: string,
  timestamp: z.ZodType,
  warn: (message: string) => void,
): string {
  if (schema === timestamp) return `${ref} is timestamp`;
  const def = schema._zod.def as { type: string; innerType?: AnySchema };
  switch (def.type) {
    case 'string':
      return `${ref} is string`;
    case 'boolean':
      return `${ref} is bool`;
    case 'number':
      return `${ref} is number`;
    case 'array':
      return `${ref} is list`;
    case 'object':
      return `${ref} is map`;
    case 'enum': {
      const options = (schema as unknown as { options: string[] }).options;
      const list = options.map((o) => `'${o}'`).join(', ');
      return `(${ref} is string && ${ref} in [${list}])`;
    }
    case 'nullable':
      return `(${ref} == null || ${typeCheck(def.innerType!, ref, timestamp, warn)})`;
    default:
      // Never emit `true` silently: a type the generator cannot map is a
      // schema the rules do not protect.
      warn(`no rules mapping for zod type '${def.type}' at ${ref}`);
      return 'false';
  }
}

/** The `function isValid<Name>(data) { ... }` source for one collection. */
export function validatorFor(
  collection: ValidatedCollection,
  timestamp: z.ZodType,
  warn: (message: string) => void = () => undefined,
): string {
  const required: string[] = [];
  const all: string[] = [];
  const checks: string[] = [];
  for (const [field, raw] of Object.entries(collection.schema.shape)) {
    const schema = raw as AnySchema;
    all.push(field);
    const def = schema._zod.def as { type: string; innerType?: AnySchema };
    const ref = `data.${field}`;
    if (def.type === 'optional') {
      checks.push(`(!('${field}' in data) || ${typeCheck(def.innerType!, ref, timestamp, warn)})`);
    } else {
      required.push(field);
      checks.push(typeCheck(schema, ref, timestamp, warn));
    }
  }
  const quote = (names: string[]) => `[${names.map((n) => `'${n}'`).join(', ')}]`;
  const lines = [
    `data.keys().hasAll(${quote(required)})`,
    `data.keys().hasOnly(${quote(all)})`,
    ...checks,
  ];
  return [
    `function isValid${collection.name}(data) {`,
    `  return ${lines.join('\n    && ')};`,
    `}`,
  ].join('\n');
}

export const BEGIN = '// AUTOGENERATED BEGIN: npm run rules:gen. Do not edit by hand.';
export const END = '// AUTOGENERATED END';

/** All validators, indented for the rules file's documents block. */
export function generatedBlock(
  collections: ValidatedCollection[],
  timestamp: z.ZodType,
  warn?: (message: string) => void,
): string {
  const body = collections.map((c) => validatorFor(c, timestamp, warn)).join('\n\n');
  return [BEGIN, body, END]
    .join('\n')
    .split('\n')
    .map((line) => (line ? `    ${line}` : line))
    .join('\n');
}

/**
 * Replaces the generated block in a rules file. Throws when the markers
 * are missing, so a hand edit that drops them is caught, not ignored.
 */
export function spliceGenerated(rules: string, block: string): string {
  const start = rules.indexOf(BEGIN);
  const end = rules.indexOf(END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error('firestore.rules is missing the AUTOGENERATED BEGIN/END markers');
  }
  const lineStart = rules.lastIndexOf('\n', start) + 1;
  return rules.slice(0, lineStart) + block + rules.slice(end + END.length);
}
